services:
  # PostgreSQL数据库
  postgres:
    image: postgres:14
    container_name: lianjia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rental_analysis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: lianjia-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./verification_sessions:/app/verification_sessions
      - ./verification_cookies:/app/verification_cookies
      - ./captcha_data:/app/captcha_data
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=rental_analysis
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: lianjia-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 